"""Initial schema

Revision ID: 791a084d54ca
Revises: 
Create Date: 2026-06-23 16:59:21.875244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '791a084d54ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'READY', 'COMPILED', 'REOPENED', name='batchstatus'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_number')
    )
    op.create_table('operators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initials', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch_headers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('product', sa.String(length=255), nullable=True),
    sa.Column('stock_item', sa.String(length=100), nullable=True),
    sa.Column('tank', sa.String(length=50), nullable=True),
    sa.Column('run_date', sa.Date(), nullable=True),
    sa.Column('packing_unit', sa.String(length=100), nullable=True),
    sa.Column('packaging_line', sa.String(length=50), nullable=True),
    sa.Column('run_quantity', sa.Integer(), nullable=True),
    sa.Column('pick_list_lines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compilations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('output_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('slot_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('compiled_by', sa.String(length=100), nullable=False),
    sa.Column('compiled_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('form_type', sa.Enum('DAILY_PRODUCTION', 'FILLER_LINE_CHECK', 'BOTTLE_SEALING', 'LABEL_USAGE', 'FINISHED_PRODUCT_LINE_CHECK', 'PICK_LIST', 'CARTON_QC', 'FINAL_PALLET_COUNT', 'FINISHED_PRODUCT_PALLET', name='formtype'), nullable=False),
    sa.Column('accrual_mode', sa.Enum('ATOMIC', 'LOG', 'MATRIX', name='accrualmode'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'EDITED_SINCE_SUBMIT', name='formstatus'), nullable=False),
    sa.Column('header_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_by', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_edited_by', sa.String(length=100), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'form_type', name='uq_batch_form_type')
    )
    op.create_table('uploaded_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Enum('EZYWINE_LISTING', 'WORK_ORDER', 'LABEL_REFERENCE', name='documentslot'), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=100), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_instance_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('operator_identifier', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['form_instance_id'], ['form_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('readings')
    op.drop_table('uploaded_documents')
    op.drop_table('form_instances')
    op.drop_table('compilations')
    op.drop_table('batch_headers')
    op.drop_table('operators')
    op.drop_table('batches')
    # ### end Alembic commands ###
