from app.forms.types import (
    FormTemplate,
    FormType,
    AccrualMode,
    FieldDef,
    FieldType,
    FieldSource,
)

FILLER_LINE_CHECK_TEMPLATE = FormTemplate(
    form_type=FormType.FILLER_LINE_CHECK,
    doc_number="FOR PK 017A",
    accrual_mode=AccrualMode.MATRIX,
    orientation="landscape",
    header_fields=[
        FieldDef(
            key="date",
            label="Date",
            field_type=FieldType.DATE,
            source=FieldSource.INHERITED,
        ),
        FieldDef(
            key="wine",
            label="Wine",
            field_type=FieldType.TEXT,
            source=FieldSource.INHERITED,
        ),
        FieldDef(
            key="tank",
            label="Tank",
            field_type=FieldType.TEXT,
            source=FieldSource.INHERITED,
        ),
        FieldDef(
            key="run_number",
            label="Run Number",
            field_type=FieldType.TEXT,
            source=FieldSource.INHERITED,
        ),
        FieldDef(
            key="filters_used",
            label="Filters used?",
            field_type=FieldType.ENUM,
            source=FieldSource.OPERATOR,
            enum_values=["45", "65", "50", "70"],
        ),
        FieldDef(
            key="correct_filters",
            label="Correct filters?",
            field_type=FieldType.BOOL,
            source=FieldSource.OPERATOR,
        ),
        FieldDef(
            key="check_filtration",
            label="Check filtration on form FOR LB 003?",
            field_type=FieldType.ENUM,
            source=FieldSource.OPERATOR,
            enum_values=["Yes", "No"],
        ),
    ],
    reading_fields=[
        FieldDef(
            key="captured_at",
            label="Time",
            field_type=FieldType.TIME,
            source=FieldSource.OPERATOR,
        ),
        FieldDef(
            key="filler_vacuum",
            label="Filler Vacuum",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
        ),
        FieldDef(
            key="rinser_all_heads",
            label="Rinser — all heads working",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
        ),
        FieldDef(
            key="filler_temperature",
            label="Filler Temperature (°C)",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
        ),
        FieldDef(
            key="fill_height",
            label="Fill Height (record 4 bottles)",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
            multi_value_count=4,
        ),
        FieldDef(
            key="dissolved_oxygen",
            label="Dissolved Oxygen (3 bottles)",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
            multi_value_count=3,
        ),
        FieldDef(
            key="redraw",
            label="Redraw (1.4–1.7 mm)",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
            multi_value_count=2,
        ),
        FieldDef(
            key="torque_bridge",
            label="Torque & Bridge (6 consecutive bottles)",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
            multi_value_count=6,
        ),
        FieldDef(
            key="bridge_inspection",
            label="Bridge Inspection (record 4 bottles)",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
            multi_value_count=4,
        ),
        FieldDef(
            key="wad_imprint",
            label="Wad Imprint Check",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
        ),
        FieldDef(
            key="initial",
            label="Initial",
            field_type=FieldType.TEXT,
            source=FieldSource.OPERATOR,
        ),
    ],
)